apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q206nz8h1-go 
  janus-idp.io/tekton: q206nz8h1-go
  backstage.io/kubernetes-id: q206nz8h1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q206nz8h1-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml